update_date: '2022-03-10'
sync_dir: '/Users/mhturner/Dropbox/ClandininLab/Analysis/glom_pop/sync'
save_directory: '/Users/mhturner/Dropbox/ClandininLab/Analysis/glom_pop/fig_panels'
included_gloms: [LC4, LC6, LC9, LC11, LC12, LC15, LC16, LC17, LC18, LC21, LC26, LC43, LPLC1, LPLC2]
